'use client'

import { useLoadEffect } from '@/hooks/use-load-effect'
import { useCallback, useState } from 'react'
import { useAppStore } from '@/lib/store'
import { supabase } from '@/lib/supabase'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Loader2, Plus, Users, Trash2, Search, UserPlus, X, GraduationCap } from 'lucide-react'
interface CI{id:string;name:string;grade:number;student_count:number}
interface SI{id:string;name:string;surname:string;student_number:string|null;grade:number|null}
export default function ClassesPage(){
  const user=useAppStore(s=>s.user)
  const [classes,setClasses]=useState<CI[]>([])
  const [allStudents,setAllStudents]=useState<SI[]>([])
  const [loading,setLoading]=useState(true)
  const [createOpen,setCreateOpen]=useState(false)
  const [newClass,setNewClass]=useState({name:'',grade:'',subject_id:'',teacher_id:''})
  const [selectedClass,setSelectedClass]=useState<CI|null>(null)
  const [classStudents,setClassStudents]=useState<SI[]>([])
  const [addStudentOpen,setAddStudentOpen]=useState(false)
  const [studentSearch,setStudentSearch]=useState('')
  const [loadingStudents,setLoadingStudents]=useState(false)
  const [subjects,setSubjects]=useState<Array<{id:string;name:string;grade:number}>>([])
  const [teachers,setTeachers]=useState<Array<{id:string;display_name:string}>>([])
  const [classAllocs,setClassAllocs]=useState<Array<{id:string;subject_name:string;teacher_name:string}>>([])
  const [addAllocOpen,setAddAllocOpen]=useState(false)
  const [allocForm,setAllocForm]=useState({subject_id:'',teacher_id:''})
  const [editingClass,setEditingClass]=useState(false)
  const [editForm,setEditForm]=useState({name:'',grade:''})
  // Bulk enroll state
  const [checkedStudents,setCheckedStudents]=useState<Set<string>>(new Set())
  const [bulkAdding,setBulkAdding]=useState(false)
  const [addMode,setAddMode]=useState<'individual'|'register'|'class'>('individual')
  const [regClassFilter,setRegClassFilter]=useState('')
  const [copySourceClass,setCopySourceClass]=useState('')
  const [copyingClass,setCopyingClass]=useState(false)

  const load = useCallback(async () => {if(!user)return;const[cR,sR,subR,tR]=await Promise.all([supabase.from('classes').select('id,name,grade').eq('school_id',user.school_id).order('grade').order('name'),supabase.from('students').select('id,name,surname,student_number,grade,register_class').eq('school_id',user.school_id).order('surname'),supabase.from('subjects').select('id,name,grade').eq('school_id',user.school_id).order('name'),supabase.from('users').select('id,display_name').eq('school_id',user.school_id).in('role',['teacher','smt','admin-teacher'])]);const allCs=[];let from=0;const size=1000;while(true){const{data}=await supabase.from('class_students').select('class_id').order('id').range(from,from+size-1);if(!data||data.length===0)break;allCs.push(...data);if(data.length<size)break;from+=size}const cm=new Map<string,number>();allCs.forEach((cs:{class_id:string})=>cm.set(cs.class_id,(cm.get(cs.class_id)||0)+1));setClasses((cR.data||[]).map((c:{id:string;name:string;grade:number})=>({...c,student_count:cm.get(c.id)||0})));if(sR.data)setAllStudents(sR.data);if(subR.data)setSubjects(subR.data);if(tR.data)setTeachers(tR.data);setLoading(false)}, [user])

  // Distinct register classes from students
  const registerClasses=[...new Set(allStudents.map(s=>(s as SI & {register_class?:string}).register_class).filter(Boolean))].sort() as string[]

  async function createClass(){if(!newClass.name||!newClass.grade||!user)return;const{data}=await supabase.from('classes').insert({name:newClass.name,grade:parseInt(newClass.grade),school_id:user.school_id}).select().single();if(data&&newClass.teacher_id)await supabase.from('allocations').insert({user_id:newClass.teacher_id,class_id:data.id,subject_id:newClass.subject_id||null});if(data){await load();setNewClass({name:'',grade:'',subject_id:'',teacher_id:''});setCreateOpen(false)}}
  async function deleteClass(id:string){await supabase.from('class_students').delete().eq('class_id',id);await supabase.from('classes').delete().eq('id',id);if(selectedClass?.id===id){setSelectedClass(null);setClassStudents([])};await load()}
  async function selectClass(cls:CI){setSelectedClass(cls);setEditForm({name:cls.name,grade:cls.grade.toString()});setEditingClass(false);setLoadingStudents(true);sessionStorage.setItem('edutrack_last_class',cls.id);const{data}=await supabase.from('class_students').select('student_id,students(id,name,surname,student_number,grade)').eq('class_id',cls.id);setClassStudents((data||[]).map((cs:Record<string,unknown>)=>cs.students as SI).filter(Boolean).sort((a,b)=>a.surname.localeCompare(b.surname)));const{data:al}=await supabase.from('allocations').select('id,subject_id,subjects(name),users!allocations_user_id_fkey(display_name)').eq('class_id',cls.id);setClassAllocs((al||[]).map((a:Record<string,unknown>)=>({id:a.id as string,subject_name:(a.subjects as{name:string})?.name||'General',teacher_name:(a.users as{display_name:string})?.display_name||'-'})));setLoadingStudents(false)}
  async function addStudentToClass(sid:string){if(!selectedClass)return;await supabase.from('class_students').upsert({student_id:sid,class_id:selectedClass.id},{onConflict:'student_id,class_id'});await selectClass(selectedClass);await load()}
  async function removeStudent(sid:string){if(!selectedClass)return;await supabase.from('class_students').delete().eq('student_id',sid).eq('class_id',selectedClass.id);setClassStudents(classStudents.filter(s=>s.id!==sid));await load()}
  async function addAlloc(){if(!selectedClass||!allocForm.teacher_id||!user)return;await supabase.from('allocations').insert({user_id:allocForm.teacher_id,class_id:selectedClass.id,subject_id:allocForm.subject_id||null});await selectClass(selectedClass);setAllocForm({subject_id:'',teacher_id:''});setAddAllocOpen(false)}
  async function removeAlloc(id:string){await supabase.from('allocations').delete().eq('id',id);setClassAllocs(classAllocs.filter(a=>a.id!==id))}

  // Bulk add selected students
  async function bulkAddChecked(){if(!selectedClass||!checkedStudents.size)return;setBulkAdding(true);await supabase.from('class_students').upsert(Array.from(checkedStudents).map(sid=>({student_id:sid,class_id:selectedClass.id})),{onConflict:'student_id,class_id'});setCheckedStudents(new Set());setAddStudentOpen(false);await selectClass(selectedClass);await load();setBulkAdding(false)}

  // Bulk add all students with a register class
  async function bulkAddByRegisterClass(){if(!selectedClass||!regClassFilter)return;setBulkAdding(true);const toAdd=allStudents.filter(s=>(s as SI&{register_class?:string}).register_class===regClassFilter&&!csIds.has(s.id));if(toAdd.length>0){await supabase.from('class_students').upsert(toAdd.map(s=>({student_id:s.id,class_id:selectedClass.id})),{onConflict:'student_id,class_id'})};setRegClassFilter('');setAddStudentOpen(false);await selectClass(selectedClass);await load();setBulkAdding(false)}

  // Copy all students from another class
  async function bulkCopyFromClass(){if(!selectedClass||!copySourceClass)return;setCopyingClass(true);const{data:srcStudents}=await supabase.from('class_students').select('student_id').eq('class_id',copySourceClass);if(srcStudents&&srcStudents.length>0){const toAdd=srcStudents.filter((cs:{student_id:string})=>!csIds.has(cs.student_id));if(toAdd.length>0)await supabase.from('class_students').upsert(toAdd.map((cs:{student_id:string})=>({student_id:cs.student_id,class_id:selectedClass.id})),{onConflict:'student_id,class_id'})};setCopySourceClass('');setAddStudentOpen(false);await selectClass(selectedClass);await load();setCopyingClass(false)}
  async function saveClassEdit(){if(!selectedClass||!editForm.name||!editForm.grade)return;await supabase.from('classes').update({name:editForm.name,grade:parseInt(editForm.grade)}).eq('id',selectedClass.id);setSelectedClass({...selectedClass,name:editForm.name,grade:parseInt(editForm.grade)});setEditingClass(false);await load()}
  const canEdit=user?.role==='admin'||user?.role==='smt'||user?.role==='admin-teacher'
  const csIds=new Set(classStudents.map(s=>s.id))
  const avail=allStudents.filter(s=>!csIds.has(s.id)&&`${s.name} ${s.surname}`.toLowerCase().includes(studentSearch.toLowerCase()))
  const gradeGroups=[...new Set(classes.map(c=>c.grade))].sort((a,b)=>a-b)

  useLoadEffect(load)

  if(loading)return<div className="flex justify-center py-12"><Loader2 className="w-8 h-8 animate-spin text-blue-500" /></div>
  return(<div className="flex flex-col lg:flex-row gap-4 lg:gap-6 lg:h-[calc(100vh-8rem)]">
    {/* Mobile class selector */}
    <div className="lg:hidden"><select value={selectedClass?.id||''} onChange={e=>{const cls=classes.find(c=>c.id===e.target.value);if(cls)selectClass(cls)}} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select a class...</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} (Gr {c.grade}) — {c.student_count} learners</option>)}</select></div>
    <div className="hidden lg:flex w-72 flex-shrink-0 flex-col"><div className="flex items-center justify-between mb-3"><h2 className="text-lg font-bold text-slate-800">Classes</h2>{canEdit&&<Button size="sm" style={{background:'#2563EB'}} onClick={()=>setCreateOpen(true)}><Plus className="w-4 h-4" /></Button>}</div><div className="flex-1 overflow-y-auto space-y-4">{gradeGroups.length===0?<p className="text-sm text-slate-400 text-center py-8">No classes yet.</p>:gradeGroups.map(grade=><div key={grade}><p className="text-xs font-semibold text-slate-500 uppercase mb-1.5 px-1">Grade {grade}</p><div className="space-y-1">{classes.filter(c=>c.grade===grade).map(cls=><button key={cls.id} onClick={()=>selectClass(cls)} className={`w-full flex items-center justify-between p-3 rounded-lg text-left text-sm ${selectedClass?.id===cls.id?'bg-blue-500 text-white shadow-sm':'bg-white text-slate-700 hover:bg-slate-50 border'}`}><div><span className="font-semibold">{cls.name}</span><span className={`ml-2 text-xs ${selectedClass?.id===cls.id?'text-blue-100':'text-slate-400'}`}>{cls.student_count} learners</span></div>{canEdit&&selectedClass?.id===cls.id&&<button onClick={e=>{e.stopPropagation();deleteClass(cls.id)}} className="text-red-200 hover:text-red-100"><Trash2 className="w-3.5 h-3.5" /></button>}</button>)}</div></div>)}</div></div>
    <div className="flex-1 min-w-0">{!selectedClass?<div className="flex flex-col items-center justify-center h-full text-slate-400"><GraduationCap className="w-16 h-16 mb-4 text-slate-200" /><p className="text-lg font-medium">Select a class</p></div>:<div className="space-y-4">
      <div className="flex items-center justify-between">{editingClass?<div className="space-y-3 w-full"><div className="grid grid-cols-2 gap-3"><div><label className="text-xs font-medium text-slate-500 mb-1 block">Name</label><Input value={editForm.name} onChange={e=>setEditForm({...editForm,name:e.target.value})} className="h-9" /></div><div><label className="text-xs font-medium text-slate-500 mb-1 block">Grade</label><select value={editForm.grade} onChange={e=>setEditForm({...editForm,grade:e.target.value})} className="w-full h-9 px-3 rounded-md border text-sm bg-white">{[1,2,3,4,5,6,7,8,9,10,11,12].map(g=><option key={g} value={g}>Grade {g}</option>)}</select></div></div><div className="flex gap-2"><Button size="sm" onClick={saveClassEdit} style={{background:'#2563EB'}}>Save</Button><Button size="sm" variant="outline" onClick={()=>setEditingClass(false)}>Cancel</Button></div></div>:<div><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-slate-800">{selectedClass.name}</h2>{canEdit&&<button onClick={()=>setEditingClass(true)} className="text-xs text-blue-600 hover:underline">Edit</button>}</div><p className="text-sm text-slate-500">Grade {selectedClass.grade} &mdash; {classStudents.length} learners</p>{classAllocs.length>0&&<div className="flex flex-wrap gap-1.5 mt-1.5">{classAllocs.map(a=><span key={a.id} className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full font-medium">{a.subject_name} ({a.teacher_name})</span>)}</div>}</div>}{canEdit&&!editingClass&&<Button size="sm" style={{background:'#8B5CF6'}} onClick={()=>{setAddStudentOpen(true);setStudentSearch('')}}><UserPlus className="w-4 h-4 mr-2" />Add Learners</Button>}</div>
      <Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-semibold text-slate-700">Subject Allocations</CardTitle>{canEdit&&<Button size="sm" variant="outline" onClick={()=>setAddAllocOpen(true)}><Plus className="w-3.5 h-3.5 mr-1" />Link</Button>}</CardHeader><CardContent>{classAllocs.length===0?<p className="text-xs text-slate-400 text-center py-3">No subjects linked.</p>:<div className="space-y-1.5">{classAllocs.map(a=><div key={a.id} className="flex items-center justify-between p-2.5 bg-blue-50 rounded-lg"><div className="flex items-center gap-3"><span className="text-sm font-medium text-slate-800">{a.subject_name}</span><span className="text-xs text-slate-400">taught by</span><span className="text-sm font-medium text-blue-600">{a.teacher_name}</span></div>{canEdit&&<button onClick={()=>removeAlloc(a.id)} className="text-red-300 hover:text-red-500"><X className="w-3.5 h-3.5" /></button>}</div>)}</div>}</CardContent></Card>
      <Card className="border-0 shadow-sm"><CardContent className="p-0">{loadingStudents?<div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin text-blue-500" /></div>:classStudents.length===0?<div className="text-center py-8 text-slate-400"><Users className="w-10 h-10 mx-auto mb-2 text-slate-200" /><p className="text-sm">No learners yet.</p></div>:<table className="w-full text-sm"><thead><tr className="border-b bg-slate-50"><th className="text-left p-3 font-medium text-slate-600">#</th><th className="text-left p-3 font-medium text-slate-600">Student</th><th className="text-left p-3 font-medium text-slate-600">ID</th>{canEdit&&<th className="p-3 w-10"></th>}</tr></thead><tbody>{classStudents.map((s,i)=><tr key={s.id} className="border-b hover:bg-slate-50"><td className="p-3 text-slate-400">{i+1}</td><td className="p-3 font-medium text-slate-800">{s.surname}, {s.name}</td><td className="p-3 text-slate-500">{s.student_number||'-'}</td>{canEdit&&<td className="p-3"><button onClick={()=>removeStudent(s.id)} className="text-red-400 hover:text-red-600"><X className="w-4 h-4" /></button></td>}</tr>)}</tbody></table>}</CardContent></Card>
    </div>}</div>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Create Class</DialogTitle></DialogHeader><div className="space-y-3 pt-2"><div><label className="text-sm font-medium mb-1 block">Grade</label><select value={newClass.grade} onChange={e=>{const g=e.target.value;setNewClass({...newClass,grade:g,name:g?`Gr ${g} A`:''})}} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select...</option>{[1,2,3,4,5,6,7,8,9,10,11,12].map(g=><option key={g} value={g}>Grade {g}</option>)}</select></div>{newClass.grade&&<div><label className="text-sm font-medium mb-1 block">Subject</label><select value={newClass.subject_id} onChange={e=>setNewClass({...newClass,subject_id:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Optional...</option>{subjects.filter(s=>s.grade===parseInt(newClass.grade)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>}<div><label className="text-sm font-medium mb-1 block">Teacher</label><select value={newClass.teacher_id} onChange={e=>setNewClass({...newClass,teacher_id:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Optional...</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select></div><div><label className="text-sm font-medium mb-1 block">Class Name</label><Input value={newClass.name} onChange={e=>setNewClass({...newClass,name:e.target.value})} placeholder="e.g. Gr 10 A" /></div><Button onClick={createClass} disabled={!newClass.name||!newClass.grade} className="w-full" style={{background:'#2563EB'}}>Create</Button></div></DialogContent></Dialog>
    <Dialog open={addStudentOpen} onOpenChange={o=>{setAddStudentOpen(o);if(!o){setCheckedStudents(new Set());setStudentSearch('');setRegClassFilter('');setCopySourceClass('');setAddMode('individual')}}}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Add Learners to {selectedClass?.name}</DialogTitle></DialogHeader><div className="pt-2 space-y-4">
        <div className="flex gap-1 bg-slate-100 p-1 rounded-lg">{(['individual','register','class'] as const).map((m,i)=><button key={m} onClick={()=>{setAddMode(m);setCheckedStudents(new Set());setStudentSearch('');setRegClassFilter('');setCopySourceClass('')}} className={`flex-1 text-xs font-medium py-1.5 rounded-md transition-all ${addMode===m?'bg-white text-slate-800 shadow-sm':'text-slate-500 hover:text-slate-700'}`}>{['Checklist','By Register Class','Copy a Class'][i]}</button>)}</div>
        {addMode==='individual'&&<><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><Input placeholder="Search learners..." value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} className="pl-9" /></div><div className="max-h-56 overflow-y-auto border rounded-lg">{avail.length===0?<p className="text-sm text-slate-400 text-center py-6">All learners already added</p>:avail.slice(0,50).map(s=><label key={s.id} className={`flex items-center gap-3 px-3 py-2.5 text-sm cursor-pointer border-b last:border-0 hover:bg-blue-50 ${checkedStudents.has(s.id)?'bg-blue-50':''}`}><input type="checkbox" checked={checkedStudents.has(s.id)} onChange={()=>{const n=new Set(checkedStudents);n.has(s.id)?n.delete(s.id):n.add(s.id);setCheckedStudents(n)}} className="w-4 h-4 rounded flex-shrink-0" /><div className="flex-1"><span className="font-medium text-slate-800">{s.surname}, {s.name}</span></div>{(s as SI&{register_class?:string|null}).register_class&&<span className="text-xs text-slate-400 bg-slate-100 px-1.5 py-0.5 rounded">{(s as SI&{register_class?:string|null}).register_class}</span>}</label>)}</div><div className="flex items-center justify-between pt-1"><button onClick={()=>setCheckedStudents(checkedStudents.size===avail.slice(0,50).length&&avail.length>0?new Set():new Set(avail.slice(0,50).map(s=>s.id)))} className="text-xs text-blue-600 hover:underline">{checkedStudents.size>0?'Deselect all':'Select all'}</button><Button onClick={bulkAddChecked} disabled={bulkAdding||!checkedStudents.size} style={{background:'#8B5CF6'}}>{bulkAdding?<Loader2 className="w-4 h-4 animate-spin mr-1" />:null}{checkedStudents.size?`Add ${checkedStudents.size} Learner${checkedStudents.size!==1?'s':''}`:'+Add Selected'}</Button></div></> }
        {addMode==='register'&&<>{registerClasses.length===0?<div className="text-sm text-amber-700 bg-amber-50 border border-amber-200 p-3 rounded-lg"><p className="font-medium mb-1">No register classes found</p><p className="text-xs">Set a learner&apos;s register class via their profile (admin only). E.g. 11E1, 8B.</p></div>:<><p className="text-sm text-slate-500">Pick a register class — every learner in it gets added to <strong>{selectedClass?.name}</strong>.</p><select value={regClassFilter} onChange={e=>setRegClassFilter(e.target.value)} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select register class...</option>{registerClasses.map(rc=>{const total=allStudents.filter(s=>(s as SI&{register_class?:string|null}).register_class===rc).length;const toAdd=allStudents.filter(s=>(s as SI&{register_class?:string|null}).register_class===rc&&!csIds.has(s.id)).length;return<option key={rc} value={rc}>{rc} — {toAdd} to add{total!==toAdd?`, ${total-toAdd} already in class`:''}</option>})}</select>{regClassFilter&&<div className="bg-purple-50 border border-purple-100 rounded-lg p-3 max-h-44 overflow-y-auto"><p className="text-xs font-semibold text-purple-700 mb-2">Will add to {selectedClass?.name}:</p>{allStudents.filter(s=>(s as SI&{register_class?:string|null}).register_class===regClassFilter&&!csIds.has(s.id)).map(s=><p key={s.id} className="text-sm text-purple-700 py-0.5">{s.surname}, {s.name}</p>)}{allStudents.filter(s=>(s as SI&{register_class?:string|null}).register_class===regClassFilter&&csIds.has(s.id)).length>0&&<p className="text-xs text-slate-400 mt-1">{allStudents.filter(s=>(s as SI&{register_class?:string|null}).register_class===regClassFilter&&csIds.has(s.id)).length} already enrolled (skipped)</p>}</div>}<Button onClick={bulkAddByRegisterClass} disabled={bulkAdding||!regClassFilter||allStudents.filter(s=>(s as SI&{register_class?:string|null}).register_class===regClassFilter&&!csIds.has(s.id)).length===0} className="w-full" style={{background:'#8B5CF6'}}>{bulkAdding?<Loader2 className="w-4 h-4 animate-spin mr-2" />:null}{regClassFilter?`Add all from ${regClassFilter}`:'Select a register class'}</Button></> }</> }
        {addMode==='class'&&<><p className="text-sm text-slate-500">Copy every learner from another class into <strong>{selectedClass?.name}</strong>. Learners already enrolled are skipped.</p><select value={copySourceClass} onChange={e=>setCopySourceClass(e.target.value)} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select source class...</option>{classes.filter(c=>c.id!==selectedClass?.id).map(c=><option key={c.id} value={c.id}>{c.name} ({c.student_count} learners)</option>)}</select>{copySourceClass&&<p className="text-xs text-slate-500 bg-slate-50 p-2 rounded">Will copy learners from <strong>{classes.find(c=>c.id===copySourceClass)?.name}</strong>. Already enrolled learners are skipped automatically.</p>}<Button onClick={bulkCopyFromClass} disabled={copyingClass||!copySourceClass} className="w-full" style={{background:'#10B981'}}>{copyingClass?<Loader2 className="w-4 h-4 animate-spin mr-2" />:null}{copySourceClass?`Copy All Learners from ${classes.find(c=>c.id===copySourceClass)?.name}`:'Copy All Learners'}</Button></> }
      </div></DialogContent></Dialog>
    <Dialog open={addAllocOpen} onOpenChange={setAddAllocOpen}><DialogContent><DialogHeader><DialogTitle>Link Subject + Teacher</DialogTitle></DialogHeader><div className="space-y-3 pt-2"><select value={allocForm.subject_id} onChange={e=>setAllocForm({...allocForm,subject_id:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Subject...</option>{subjects.filter(s=>!selectedClass||s.grade===selectedClass.grade).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={allocForm.teacher_id} onChange={e=>setAllocForm({...allocForm,teacher_id:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Teacher...</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select><Button onClick={addAlloc} disabled={!allocForm.teacher_id} className="w-full" style={{background:'#2563EB'}}>Link</Button></div></DialogContent></Dialog>
  </div>)
}

