'use client'
import { useEffect, useState } from 'react'
import { useAppStore } from '@/lib/store'
import { supabase } from '@/lib/supabase'
import Link from 'next/link'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Loader2, Upload, Search, Plus, Camera, MoveRight, Images } from 'lucide-react'
import * as XLSX from 'xlsx'
interface SR {id:string;student_number:string|null;name:string;surname:string;grade:number|null;photo_url:string|null;register_class?:string|null;classes?:string[]}
export default function StudentsPage() {
  const user = useAppStore(s=>s.user)
  const [students,setStudents]=useState<SR[]>([])
  const [classes,setClasses]=useState<Array<{id:string;name:string;grade:number}>>([])
  const [loading,setLoading]=useState(true)
  const [search,setSearch]=useState('')
  const [gradeFilter,setGradeFilter]=useState<number|'all'>('all')
  const [addOpen,setAddOpen]=useState(false)
  const [uploadOpen,setUploadOpen]=useState(false)
  const [photoOpen,setPhotoOpen]=useState<string|null>(null)
  const [newStudent,setNewStudent]=useState({name:'',surname:'',student_number:'',grade:'',class_id:''})
  const [sheetData,setSheetData]=useState<Record<string,string>[]>([])
  const [sheetCols,setSheetCols]=useState<string[]>([])
  const [mapping,setMapping]=useState({id_col:'',name_col:'',surname_col:'',combined_name:false,grade_col:''})
  const [mappingStep,setMappingStep]=useState(false)
  const [uploading,setUploading]=useState(false)
  const [selected,setSelected]=useState<Set<string>>(new Set())
  const [bulkOpen,setBulkOpen]=useState(false)
  const [bulkClass,setBulkClass]=useState('')
  const [moveStudent,setMoveStudent]=useState<SR|null>(null)
  const [moveTarget,setMoveTarget]=useState('')
  const [moving,setMoving]=useState(false)
  const [bulkPhotoOpen,setBulkPhotoOpen]=useState(false)
  const [bulkPhotoFiles,setBulkPhotoFiles]=useState<File[]>([])
  const [bulkPhotoBusy,setBulkPhotoBusy]=useState(false)
  const [bulkPhotoResult,setBulkPhotoResult]=useState<{matched:number;unmatched:string[]}|null>(null)
  useEffect(()=>{if(user)load()},[user])
  async function load(){
    if(!user)return
    const[sR,cR]=await Promise.all([
      supabase.from('students').select('id,student_number,name,surname,grade,photo_url,register_class').eq('school_id',user.school_id).order('surname'),
      supabase.from('classes').select('id,name,grade').eq('school_id',user.school_id).order('grade').order('name'),
    ])
    const studentList = (sR.data||[]) as SR[]
    const ids = studentList.map(s=>s.id)
    let cm = new Map<string,string[]>()
    if(ids.length>0){
      const{data:csData}=await supabase.from('class_students').select('student_id,classes(name)').in('student_id',ids)
      ;(csData||[]).forEach((c:Record<string,unknown>)=>{const sid=c.student_id as string;const cn=(c.classes as{name:string})?.name||'';if(!cm.has(sid))cm.set(sid,[]);cm.get(sid)!.push(cn)})
    }
    setStudents(studentList.map((s)=>({...s,classes:cm.get(s.id)||[]})))
    if(cR.data)setClasses(cR.data)
    setLoading(false)
  }
  function handleFile(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=(ev)=>{const wb=XLSX.read(ev.target?.result,{type:'binary'});const j=XLSX.utils.sheet_to_json<Record<string,string>>(wb.Sheets[wb.SheetNames[0]]);if(j.length>0){setSheetData(j);setSheetCols(Object.keys(j[0]));const c=Object.keys(j[0]).map(k=>k.toLowerCase());setMapping({id_col:Object.keys(j[0]).find(k=>c[Object.keys(j[0]).indexOf(k)]?.includes('id'))||'',name_col:Object.keys(j[0]).find(k=>c[Object.keys(j[0]).indexOf(k)]?.includes('name')&&!c[Object.keys(j[0]).indexOf(k)]?.includes('sur'))||'',surname_col:Object.keys(j[0]).find(k=>c[Object.keys(j[0]).indexOf(k)]?.includes('surname'))||'',combined_name:false,grade_col:Object.keys(j[0]).find(k=>c[Object.keys(j[0]).indexOf(k)]?.includes('grade'))||''});setMappingStep(true)}};r.readAsBinaryString(f)}
  async function importStudents(){if(!user||!sheetData.length)return;setUploading(true);const recs=sheetData.map(row=>{let n='',s='';if(mapping.combined_name){const f=(row[mapping.name_col]||'').trim().split(' ');n=f[0]||'';s=f.slice(1).join(' ')||''}else{n=(row[mapping.name_col]||'').trim();s=(row[mapping.surname_col]||'').trim()};return{student_number:row[mapping.id_col]||null,name:n,surname:s,grade:mapping.grade_col?parseInt(row[mapping.grade_col])||null:null,school_id:user.school_id}}).filter(r=>r.name&&r.surname);await supabase.from('students').insert(recs);await load();setUploadOpen(false);setSheetData([]);setMappingStep(false);setUploading(false)}
  async function addStudent(){if(!user||!newStudent.name||!newStudent.surname)return;const{data}=await supabase.from('students').insert({name:newStudent.name,surname:newStudent.surname,student_number:newStudent.student_number||null,grade:newStudent.grade?parseInt(newStudent.grade):null,school_id:user.school_id}).select().single();if(data&&newStudent.class_id)await supabase.from('class_students').insert({student_id:data.id,class_id:newStudent.class_id});if(data){await load();setAddOpen(false);setNewStudent({name:'',surname:'',student_number:'',grade:'',class_id:''})}}
  async function uploadPhoto(sid:string,file:File){const p=`${sid}.${file.name.split('.').pop()}`;const{error}=await supabase.storage.from('student-photos').upload(p,file,{upsert:true});if(!error){const{data:u}=supabase.storage.from('student-photos').getPublicUrl(p);await supabase.from('students').update({photo_url:u.publicUrl+'?t='+Date.now()}).eq('id',sid);await load()};setPhotoOpen(null)}
  async function bulkAssign(){if(!bulkClass||!selected.size)return;await supabase.from('class_students').upsert(Array.from(selected).map(sid=>({student_id:sid,class_id:bulkClass})),{onConflict:'student_id,class_id'});await load();setBulkOpen(false);setSelected(new Set())}
  async function moveRegisterClass(){if(!moveStudent||!moveTarget)return;setMoving(true);const gradeMatch=moveTarget.match(/^(\d+)/);const grade=gradeMatch?parseInt(gradeMatch[1]):moveStudent.grade;await supabase.from('students').update({register_class:moveTarget,grade:grade}).eq('id',moveStudent.id);await load();setMoveStudent(null);setMoveTarget('');setMoving(false)}
  function normalizeNumber(fn:string){const base=fn.replace(/\.[^.]+$/,'');const nums=base.match(/\d+/g);if(!nums)return base.trim();return nums.sort((a,b)=>b.length-a.length)[0]}
  async function bulkUploadPhotos(){if(!user||!bulkPhotoFiles.length)return;setBulkPhotoBusy(true);setBulkPhotoResult(null);const byNum=new Map<string,SR>();for(const s of students){if(s.student_number){const k=s.student_number.trim();if(k){byNum.set(k,s);const z=k.replace(/^0+/,'');if(z)byNum.set(z,s)}}}
    let matched=0;const unmatched:string[]=[];for(const file of bulkPhotoFiles){const num=normalizeNumber(file.name);const st=byNum.get(num)||byNum.get(num.replace(/^0+/,''));if(!st){unmatched.push(file.name);continue}const p=`${st.id}.${file.name.split('.').pop()}`;const{error}=await supabase.storage.from('student-photos').upload(p,file,{upsert:true});if(!error){const{data:u}=supabase.storage.from('student-photos').getPublicUrl(p);await supabase.from('students').update({photo_url:u.publicUrl+'?t='+Date.now()}).eq('id',st.id);matched++}else{unmatched.push(file.name)}}
    setBulkPhotoResult({matched,unmatched});setBulkPhotoBusy(false);setBulkPhotoFiles([]);await load()}
  const grades=[...new Set(students.map(s=>s.grade).filter(Boolean))].sort((a,b)=>(a||0)-(b||0)) as number[]
  const registerClasses=[...new Set(students.map(s=>s.register_class).filter(Boolean))].sort() as string[]
  const filtered=students.filter(s=>`${s.name} ${s.surname} ${s.student_number||''}`.toLowerCase().includes(search.toLowerCase())&&(gradeFilter==='all'||s.grade===gradeFilter))
  const canEdit=user?.role==='admin'||user?.role==='smt'||user?.role==='admin-teacher'
  if(!user)return null
  return(<div className="space-y-4">
    <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between"><div className="relative flex-1 max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><Input placeholder="Search students..." value={search} onChange={e=>setSearch(e.target.value)} className="pl-9" /></div>{canEdit&&<div className="flex gap-2 flex-wrap"><Button size="sm" variant="outline" onClick={()=>setUploadOpen(true)}><Upload className="w-4 h-4 mr-2" />Upload</Button><Button size="sm" variant="outline" onClick={()=>{setBulkPhotoFiles([]);setBulkPhotoResult(null);setBulkPhotoOpen(true)}}><Images className="w-4 h-4 mr-2" />Bulk Photos</Button><Button size="sm" style={{background:'#2563EB'}} onClick={()=>setAddOpen(true)}><Plus className="w-4 h-4 mr-2" />Add</Button></div>}</div>
    <div className="flex items-center justify-between">
      <div className="flex gap-1 flex-wrap">
        <button onClick={()=>setGradeFilter('all')} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${gradeFilter==='all'?'bg-blue-500 text-white':'bg-white text-slate-600 hover:bg-slate-100 border'}`}>All ({students.length})</button>
        {grades.map(g=><button key={g} onClick={()=>setGradeFilter(g)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${gradeFilter===g?'bg-blue-500 text-white':'bg-white text-slate-600 hover:bg-slate-100 border'}`}>Gr {g} ({students.filter(s=>s.grade===g).length})</button>)}
      </div>
      <span className="text-xs text-slate-400">{filtered.length} showing</span>
    </div>
    {selected.size>0&&canEdit&&<div className="flex items-center gap-3 p-3 bg-blue-50 rounded-lg border border-blue-200"><span className="text-sm font-medium text-blue-700">{selected.size} selected</span><Button size="sm" style={{background:'#8B5CF6'}} onClick={()=>setBulkOpen(true)}>Add to Class</Button><Button size="sm" variant="ghost" onClick={()=>setSelected(new Set())}>Clear</Button></div>}
    <Card className="border-0 shadow-sm"><CardContent className="p-0">{loading?<div className="flex justify-center py-12"><Loader2 className="w-8 h-8 animate-spin text-blue-500" /></div>:filtered.length===0?<p className="text-center text-slate-400 py-12">No students found.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-slate-50">{canEdit&&<th className="p-3 w-10"><input type="checkbox" checked={selected.size===filtered.length&&filtered.length>0} onChange={()=>selected.size===filtered.length?setSelected(new Set()):setSelected(new Set(filtered.map(s=>s.id)))} className="w-4 h-4" /></th>}<th className="text-left p-3 font-medium text-slate-600">Photo</th><th className="text-left p-3 font-medium text-slate-600">Student</th><th className="text-left p-3 font-medium text-slate-600">ID</th><th className="text-left p-3 font-medium text-slate-600">Grade</th><th className="text-left p-3 font-medium text-slate-600">Register Class</th><th className="text-left p-3 font-medium text-slate-600">Classes</th>{canEdit&&<th className="p-3">Actions</th>}</tr></thead><tbody>{filtered.map(s=><tr key={s.id} className={`border-b hover:bg-slate-50 ${selected.has(s.id)?'bg-blue-50':''}`}>{canEdit&&<td className="p-3"><input type="checkbox" checked={selected.has(s.id)} onChange={()=>{const n=new Set(selected);n.has(s.id)?n.delete(s.id):n.add(s.id);setSelected(n)}} className="w-4 h-4" /></td>}<td className="p-3">{s.photo_url?<img src={s.photo_url} alt="" className="w-10 h-10 rounded-full object-cover" />:<div className="w-10 h-10 rounded-full bg-slate-200 flex items-center justify-center text-xs font-bold text-slate-500">{s.name.charAt(0)}{s.surname.charAt(0)}</div>}</td><td className="p-3"><Link href={`/dashboard/students/${s.id}`} className="font-medium text-blue-600 hover:underline">{s.surname}, {s.name}</Link></td><td className="p-3 text-slate-500">{s.student_number||'-'}</td><td className="p-3 text-slate-500">{s.grade||'-'}</td><td className="p-3">{s.register_class?<span className="text-xs bg-purple-50 text-purple-700 px-2 py-0.5 rounded-full font-medium">{s.register_class}</span>:<span className="text-slate-400">-</span>}</td><td className="p-3"><div className="flex flex-wrap gap-1">{(s.classes||[]).map((c,i)=><span key={i} className="text-xs bg-blue-50 text-blue-600 px-2 py-0.5 rounded-full">{c}</span>)}</div></td>{canEdit&&<td className="p-3"><div className="flex items-center gap-1"><Button variant="ghost" size="sm" onClick={()=>{setMoveStudent(s);setMoveTarget('')}} title="Move register class"><MoveRight className="w-4 h-4" /></Button><Button variant="ghost" size="sm" onClick={()=>setPhotoOpen(s.id)}><Camera className="w-4 h-4" /></Button></div></td>}</tr>)}</tbody></table></div>}</CardContent></Card>
    {photoOpen&&<Dialog open={!!photoOpen} onOpenChange={()=>setPhotoOpen(null)}><DialogContent><DialogHeader><DialogTitle>Upload Photo</DialogTitle></DialogHeader><input type="file" accept="image/*" onChange={e=>{if(e.target.files?.[0]&&photoOpen)uploadPhoto(photoOpen,e.target.files[0])}} /></DialogContent></Dialog>}
    <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>Add Student</DialogTitle></DialogHeader><div className="space-y-3 pt-2"><Input placeholder="First Name" value={newStudent.name} onChange={e=>setNewStudent({...newStudent,name:e.target.value})} /><Input placeholder="Surname" value={newStudent.surname} onChange={e=>setNewStudent({...newStudent,surname:e.target.value})} /><Input placeholder="Student Number" value={newStudent.student_number} onChange={e=>setNewStudent({...newStudent,student_number:e.target.value})} /><Input type="number" placeholder="Grade" value={newStudent.grade} onChange={e=>setNewStudent({...newStudent,grade:e.target.value})} /><select value={newStudent.class_id} onChange={e=>setNewStudent({...newStudent,class_id:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Class (optional)</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Button onClick={addStudent} className="w-full" style={{background:'#2563EB'}}>Add</Button></div></DialogContent></Dialog>
    <Dialog open={uploadOpen} onOpenChange={o=>{setUploadOpen(o);if(!o){setSheetData([]);setMappingStep(false)}}}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Upload Spreadsheet</DialogTitle></DialogHeader>{!mappingStep?<div className="space-y-4 pt-2"><p className="text-sm text-slate-500">Upload Excel/CSV with student data.</p><input type="file" accept=".xlsx,.xls,.csv" onChange={handleFile} className="text-sm" /></div>:<div className="space-y-3 pt-2"><p className="text-sm text-slate-500">{sheetData.length} rows detected.</p><div><label className="text-sm font-medium mb-1 block">ID Column</label><select value={mapping.id_col} onChange={e=>setMapping({...mapping,id_col:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">None</option>{sheetCols.map(c=><option key={c} value={c}>{c}</option>)}</select></div><div><label className="text-sm font-medium mb-1 block">Name Column</label><select value={mapping.name_col} onChange={e=>setMapping({...mapping,name_col:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select</option>{sheetCols.map(c=><option key={c} value={c}>{c}</option>)}</select></div><div><label className="text-sm font-medium mb-1 block">Surname Column</label><select value={mapping.surname_col} onChange={e=>setMapping({...mapping,surname_col:e.target.value})} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select</option>{sheetCols.map(c=><option key={c} value={c}>{c}</option>)}</select></div><Button onClick={importStudents} disabled={uploading} className="w-full" style={{background:'#2563EB'}}>{uploading?<Loader2 className="w-4 h-4 animate-spin mr-2" />:null}Import {sheetData.length} Students</Button></div>}</DialogContent></Dialog>
    <Dialog open={bulkPhotoOpen} onOpenChange={o=>{setBulkPhotoOpen(o);if(!o){setBulkPhotoFiles([]);setBulkPhotoResult(null)}}}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Bulk Upload Photos</DialogTitle></DialogHeader><div className="space-y-3 pt-2"><p className="text-sm text-slate-500">Select many photo files at once. Each filename should contain the student number (e.g. <span className="font-semibold">4536.jpg</span>) so it can be matched to the right student.</p><input type="file" accept="image/*" multiple onChange={e=>{if(e.target.files){setBulkPhotoFiles(Array.from(e.target.files));setBulkPhotoResult(null)}}} className="text-sm" />{bulkPhotoFiles.length>0&&!bulkPhotoBusy&&!bulkPhotoResult&&<div className="text-sm text-slate-600">{bulkPhotoFiles.length} files selected. <Button size="sm" onClick={bulkUploadPhotos} style={{background:'#2563EB'}}>Upload and match</Button></div>}{bulkPhotoBusy&&<div className="flex items-center gap-2 text-sm text-blue-600"><Loader2 className="w-4 h-4 animate-spin" />Uploading {bulkPhotoFiles.length} photos...</div>}{bulkPhotoResult&&<div className="space-y-2"><p className="text-sm font-medium text-slate-800">{bulkPhotoResult.matched} photo(s) matched and uploaded.</p>{bulkPhotoResult.unmatched.length>0&&<div><p className="text-xs text-slate-500 mb-1">These could not be matched to a student number:</p><div className="max-h-32 overflow-y-auto text-xs text-red-600 bg-red-50 p-2 rounded">{bulkPhotoResult.unmatched.map((f,i)=><div key={i}>{f}</div>)}</div></div>}<Button variant="outline" size="sm" onClick={()=>setBulkPhotoOpen(false)}>Done</Button></div>}</div></DialogContent></Dialog>
    <Dialog open={!!moveStudent} onOpenChange={()=>setMoveStudent(null)}><DialogContent><DialogHeader><DialogTitle>Move Register Class</DialogTitle></DialogHeader><div className="space-y-3 pt-2">{moveStudent&&<div className="p-2 bg-purple-50 rounded text-sm font-medium">{moveStudent.surname}, {moveStudent.name} <span className="text-purple-600">· currently {moveStudent.register_class||'no register class'}</span></div>}<p className="text-sm text-slate-500">Moving the register class updates where they appear on the attendance register. Past marks stay unchanged.</p><select value={moveTarget} onChange={e=>setMoveTarget(e.target.value)} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select new register class...</option>{registerClasses.filter(r=>r!==moveStudent?.register_class).map(r=><option key={r} value={r}>{r}</option>)}</select><Input placeholder="Or type a new register class (e.g. 11E2)" value={moveTarget} onChange={e=>setMoveTarget(e.target.value)} /><Button onClick={moveRegisterClass} disabled={moving||!moveTarget} className="w-full" style={{background:'#8B5CF6'}}>{moving?<Loader2 className="w-4 h-4 animate-spin mr-2" />:null}Move to {moveTarget||'...'}</Button><Button variant="outline" onClick={()=>setMoveStudent(null)} className="w-full">Cancel</Button></div></DialogContent></Dialog>
    <Dialog open={bulkOpen} onOpenChange={setBulkOpen}><DialogContent><DialogHeader><DialogTitle>Add {selected.size} to Class</DialogTitle></DialogHeader><div className="space-y-3 pt-2"><select value={bulkClass} onChange={e=>setBulkClass(e.target.value)} className="w-full h-10 px-3 rounded-md border text-sm bg-white"><option value="">Select class...</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Button onClick={bulkAssign} disabled={!bulkClass} className="w-full" style={{background:'#8B5CF6'}}>Assign</Button></div></DialogContent></Dialog>
  </div>)
}

