'use client'

import { useLoadEffect } from '@/hooks/use-load-effect'
import { useCallback, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { useAppStore } from '@/lib/store'
import { supabase } from '@/lib/supabase'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Loader2, ArrowLeft, Download, Check, X, Clock } from 'lucide-react'
export default function StudentAttendanceReport(){const params=useParams();const router=useRouter();const user=useAppStore(s=>s.user);const studentId=params.id as string;const[student,setStudent]=useState<{name:string;surname:string;student_number:string;grade:number|null}|null>(null);const[records,setRecords]=useState<Array<{date:string;period:number;status:string;class_name:string}>>([]);const[loading,setLoading]=useState(true);const[dateFrom,setDateFrom]=useState(()=>{const d=new Date();d.setMonth(d.getMonth()-1);return d.toISOString().split('T')[0]});const[dateTo,setDateTo]=useState(()=>new Date().toISOString().split('T')[0])

  const load = useCallback(async () => {if(!user)return;setLoading(true);const[sR,aR]=await Promise.all([supabase.from('students').select('name,surname,student_number,grade').eq('id',studentId).single(),supabase.from('attendance').select('date,period,status,classes(name)').eq('student_id',studentId).gte('date',dateFrom).lte('date',dateTo).order('date',{ascending:false}).order('period')]);if(sR.data)setStudent(sR.data);setRecords((aR.data||[]).map((r:Record<string,unknown>)=>({date:r.date as string,period:r.period as number,status:r.status as string,class_name:(r.classes as{name:string})?.name||''})));setLoading(false)}, [user, studentId, dateFrom, dateTo])

  const present=records.filter(r=>r.status==='present').length;const absent=records.filter(r=>r.status==='absent').length;const late=records.filter(r=>r.status==='late').length;const total=records.length;const pPct=total>0?Math.round((present/total)*100):0;const aPct=total>0?Math.round((absent/total)*100):0;const lPct=total>0?Math.round((late/total)*100):0
  function exportPDF(){if(!student)return;const rows=records.map(r=>`<tr><td>${r.date}</td><td>P${r.period}</td><td>${r.class_name}</td><td class="${r.status}">${r.status.toUpperCase()}</td></tr>`).join('');const html=`<!DOCTYPE html><html><head><title>Attendance - ${student.surname}, ${student.name}</title><style>body{font-family:Arial;padding:30px;max-width:800px;margin:0 auto}h1{font-size:20px}.meta{font-size:12px;color:#94a3b8;margin-bottom:16px}.stats{display:flex;gap:12px;margin:16px 0}.stat{flex:1;text-align:center;padding:12px;border-radius:8px;font-size:12px}.stat b{display:block;font-size:22px}.s-green{background:#dcfce7;color:#16a34a}.s-red{background:#fef2f2;color:#dc2626}.s-yellow{background:#fefce8;color:#ca8a04}.s-blue{background:#eff6ff;color:#2563eb}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #e2e8f0;padding:6px 10px;text-align:left}th{background:#f8fafc}.present{color:#16a34a;font-weight:600}.absent{color:#dc2626;font-weight:600}.late{color:#ca8a04;font-weight:600}.note{margin-top:20px;padding:12px;background:#f8fafc;border-radius:8px;font-size:11px;color:#64748b}</style></head><body><h1>Student Attendance Report</h1><p class="meta">${student.surname}, ${student.name} | ${dateFrom} to ${dateTo}</p><div class="stats"><div class="stat s-green"><b>${pPct}%</b>Present (${present})</div><div class="stat s-red"><b>${aPct}%</b>Absent (${absent})</div><div class="stat s-yellow"><b>${lPct}%</b>Late (${late})</div></div><table><thead><tr><th>Date</th><th>Period</th><th>Class</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table><div class="note"><b>Note:</b> Contact the school if you have concerns.</div></body></html>`;const w=window.open('','_blank');if(w){w.document.write(html);w.document.close();w.setTimeout(()=>w.print(),500)}}

  useLoadEffect(load)

  if(loading)return<div className="flex justify-center py-12"><Loader2 className="w-8 h-8 animate-spin text-blue-500" /></div>
  if(!student)return<div className="text-center py-12 text-slate-500">Not found</div>
  return(<div className="max-w-3xl space-y-6">
    <div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={()=>router.back()}><ArrowLeft className="w-5 h-5" /></Button><div><h2 className="text-xl font-bold text-slate-800">Attendance Report</h2><p className="text-sm text-slate-500">{student.surname}, {student.name}</p></div></div>
    <Card className="border-0 shadow-sm"><CardContent className="pt-5"><div className="flex flex-col sm:flex-row gap-3 items-end"><div className="flex-1"><label className="text-xs font-medium text-slate-500 mb-1 block">From</label><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="w-full h-10 px-3 rounded-md border text-sm bg-white" /></div><div className="flex-1"><label className="text-xs font-medium text-slate-500 mb-1 block">To</label><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="w-full h-10 px-3 rounded-md border text-sm bg-white" /></div><Button onClick={exportPDF} className="w-full sm:w-auto h-10" style={{background:'#2563EB'}}><Download className="w-4 h-4 mr-2" />Export for Parents</Button></div></CardContent></Card>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Card className="border-0 shadow-sm" style={{borderLeft:'4px solid #10B981'}}><CardContent className="pt-4 pb-3 text-center"><p className="text-3xl font-bold text-green-600">{pPct}%</p><p className="text-xs text-slate-500">Present ({present})</p></CardContent></Card><Card className="border-0 shadow-sm" style={{borderLeft:'4px solid #EF4444'}}><CardContent className="pt-4 pb-3 text-center"><p className="text-3xl font-bold text-red-600">{aPct}%</p><p className="text-xs text-slate-500">Absent ({absent})</p></CardContent></Card><Card className="border-0 shadow-sm" style={{borderLeft:'4px solid #F59E0B'}}><CardContent className="pt-4 pb-3 text-center"><p className="text-3xl font-bold text-yellow-600">{lPct}%</p><p className="text-xs text-slate-500">Late ({late})</p></CardContent></Card><Card className="border-0 shadow-sm" style={{borderLeft:'4px solid #2563EB'}}><CardContent className="pt-4 pb-3 text-center"><p className="text-3xl font-bold text-blue-600">{total}</p><p className="text-xs text-slate-500">Total Marks</p></CardContent></Card></div>
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle>Records ({records.length})</CardTitle></CardHeader><CardContent className="p-0">{records.length===0?<p className="text-sm text-slate-400 text-center py-8">No records</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-slate-50"><th className="text-left p-3 font-medium text-slate-600">Date</th><th className="text-left p-3 font-medium text-slate-600">Period</th><th className="text-left p-3 font-medium text-slate-600">Class</th><th className="text-left p-3 font-medium text-slate-600">Status</th></tr></thead><tbody>{records.map((r,i)=><tr key={i} className={`border-b ${r.status==='absent'?'bg-red-50/50':r.status==='late'?'bg-yellow-50/50':''}`}><td className="p-3 text-slate-600">{new Date(r.date+'T00:00').toLocaleDateString('en-ZA',{day:'numeric',month:'short',weekday:'short'})}</td><td className="p-3">Period {r.period}</td><td className="p-3 text-slate-500">{r.class_name}</td><td className="p-3"><span className={`inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full ${r.status==='present'?'bg-green-100 text-green-700':r.status==='absent'?'bg-red-100 text-red-700':'bg-yellow-100 text-yellow-700'}`}>{r.status==='present'?<Check className="w-3 h-3" />:r.status==='absent'?<X className="w-3 h-3" />:<Clock className="w-3 h-3" />}{r.status.toUpperCase()}</span></td></tr>)}</tbody></table></div>}</CardContent></Card>
  </div>)
}

